openapi: 3.0.0
info:
  description: This API recieves order events from mobile devices
  version: "1.0.0"
  title: Order API
  contact:
    email: hanantharajah@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: devices
    description: Operations available to mobile devices
paths:
  /orders/food-delivery:
    post:
      tags:
        - devices
      summary: reports a food delivery order
      operationId: app.report_food_order
      description: Adds a new food order to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FoodOrder'
        description: Inventory item to add
  /orders/scheduled-delivery:
    post:
      tags:
        - devices
      summary: reports a scheduled food order delivery
      operationId: app.report_scheduled_order
      description: Adds a new scheduled order to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduledOrder'
        description: Order item to add
components:
  schemas:
    FoodOrder:
      type: object
      required:
        - customer_id
        - name
        - phone
        - order_date
      properties:
        customer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: John Wall
        order_date:
          type: string
          format: date-time
          example: '2016-08-29 09:12:33.088831'
        phone:
          type: string
          example: 408-867-5309

    ScheduledOrder:
      required:
        - customer_id
        - name
        - phone
        - order_date
        - scheduled_date
      properties:
        customer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: John Wall
        order_date:
          type: string
          format: date-time
          example: '2016-08-29 09:12:33.088831'
        scheduled_date:
          type: string
          format: date-time
          example: '2017-08-29 09:12:33.088831'
        phone:
          type: string
          example: 408-867-5309
      type: object
#servers:
#  # Added by API Auto Mocking Plugin
#  - description: SwaggerHub API Auto Mocking
#    url: https://virtserver.swaggerhub.com/harish5/Orders/1.0.0